# image: "playground_demo.pgm" # Using the same map file
image: "/home/ubuntu/repos/SMAC_that_planner-playground/ros_ws/planner_playground/config/playground_demo.pgm"
resolution: 0.01 # Each pixel now represents 5mm (0.005 m), making the map scale 10x smaller
origin: [-3.0, -2.0, 0.0] # The (x, y) coordinate of the bottom-left of the map; adjust as needed
occupied_thresh: 0.65 # Pixels with a value > 0.65 are considered occupied
free_thresh: 0.196 # Pixels with a value < 0.196 are considered frees
negate: 0 # 0: white is free, black is occupied