# ---------------------------------------------------------------------------- #
#                         config from plannerplayground                        #
# # ---------------------------------------------------------------------------- #
# image: map.png
# resolution: 0.05
# origin: [0.0, 0.0, 0.0]
# occupied_thresh: 0.65
# free_thresh: 0.1
# negate: 0
# mode: trinary


# ---------------------------------------------------------------------------- #
#                             adjusted for test map                            #
# ---------------------------------------------------------------------------- #
image: "/home/ubuntu/edward/ros2_ws/src/nav2_kas/maps/kasv1_1.png" # Using the same map file
resolution: 0.01 #0.05
origin: [0.0, 0.0, 0.0]
occupied_thresh: 0.65
free_thresh: 0.1
negate: 0
mode: trinary

# ---------------------------------------------------------------------------- #
#                            playground testing map                            #
# ---------------------------------------------------------------------------- #
# image: "/home/ubuntu/edward/ros2_ws/src/nav2_kas/maps/playground_demo.pgm" # Using the same map file
# resolution: 0.01 # Each pixel now represents 5mm (0.005 m), making the map scale 10x smaller
# origin: [-3.0, -2.0, 0.0] # The (x, y) coordinate of the bottom-left of the map; adjust as needed
# negate: 0 # 0: white is free, black is occupied
# occupied_thresh: 0.65 # Pixels with a value > 0.65 are considered occupied
# free_thresh: 0.196 # Pixels with a value < 0.196 are considered free


#map v3
# image: "/home/ubuntu/edward/ros2_ws/src/nav2_kas/maps/kasv1.pgm" # Using the same map file
# resolution: 0.01 # Each pixel now represents 5mm (0.005 m), making the map scale 10x smaller
# origin: [-3.0, -2.0, 0.0] # The (x, y) coordinate of the bottom-left of the map; adjust as needed
# negate: 0 # 0: white is free, black is occupied
# occupied_thresh: 0.65 # Pixels with a value > 0.65 are considered occupied
# free_thresh: 0.196 # Pixels with a value < 0.196 are considered free
# ---------------------------------------------------------------------------- #
#                                    map v2                                    #
# ---------------------------------------------------------------------------- #
# image: "/home/ubuntu/edward/ros2_ws/src/nav2_kas/maps/my_mapv2.pgm" # Using the same map file
# resolution: 0.01 # Each pixel now represents 5mm (0.005 m), making the map scale 10x smaller
# origin: [-3.0, -2.0, 0.0] # The (x, y) coordinate of the bottom-left of the map; adjust as needed
# negate: 0 # 0: white is free, black is occupied
# occupied_thresh: 0.65 # Pixels with a value > 0.65 are considered occupied
# free_thresh: 0.196 # Pixels with a value < 0.196 are considered free

# ---------------------------------------------------------------------------- #
#                                    map v1                                    #
# ---------------------------------------------------------------------------- #
# image: "/home/ubuntu/edward/ros2_ws/src/nav2_kas/maps/my_map.pgm" # Using the same map file
# resolution: 0.005 # Each pixel now represents 5mm (0.005 m?), making the map scale 10x smaller
# origin: [-3.0, -3.0, 0.0] # The (x, y) coordinate of the bottom-left of the map; adjust as needed
# negate: 0 # 0: white is free, black is occupied
# occupied_thresh: 0.65 # Pixels with a value > 0.65 are considered occupied
# free_thresh: 0.196 # Pixels with a value < 0.196 are considered free
